# Two pods, one container each
# Each container asking for 1 distinct GPU

---
apiVersion: v1
kind: Namespace
metadata:
  name: cpu-test

---
apiVersion: resource.k8s.io/v1alpha3
kind: ResourceClaimTemplate
metadata:
  namespace: cpu-test
  name: cpu.nvidia.com
spec:
  spec:
    devices:
      requests:
        - name: cpu
          deviceClassName: cpu.nvidia.com
          count: 16
          allocationMode: ExactCount
      constraints:
      - matchAttribute:
          "dra.nvidia.com/numa"
        requests:
          - cpu


---
apiVersion: v1
kind: Pod
metadata:
  namespace: cpu-test
  name: pod0
  labels:
    app: pod
spec:
  containers:
    - name: ctr0
      image: ubuntu:22.04
      command: ["bash", "-c"]
      args: ["export; sleep 9999"]
      resources:
        claims:
          - name: cpu
  resourceClaims:
    - name: cpu
      resourceClaimTemplateName: cpu.nvidia.com